#!/usr/bin/env python3
"""Shared semantic palette for generated maps and the website."""
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def load_palette(root: Path = ROOT) -> dict:
    palette = json.loads((root / "data/color-system.json").read_text())
    expected = {"planned", "optional", "logistics", "reference", "drive", "rest", "check", "no-fly"}
    if set(palette) != expected:
        raise ValueError("Missing or unexpected semantic color role")
    for role, values in palette.items():
        if set(values) != {"color", "tint"} or not all(re.fullmatch(r"#[0-9A-F]{6}", value) for value in values.values()):
            raise ValueError(f"Invalid palette entry: {role}")
    return palette


def generated_css(root: Path = ROOT) -> str:
    lines = ["/* Generated by scripts/build_colors.py; edit data/color-system.json. */", ":root {"]
    for role, values in load_palette(root).items():
        lines.extend(f"  --semantic-{role}-{kind}: {value};" for kind, value in values.items())
    return "\n".join(lines + ["}", ""])


if __name__ == "__main__":
    (ROOT / "assets/colors.css").write_text(generated_css(), encoding="utf-8")
    print("Generated assets/colors.css from shared palette")
